set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -g mouse on
setw -g mode-keys vi
set-option -g default-command $SHELL                        
set -g @plugin 'Nybkox/tmux-kanagawa'
set -g @kanagawa-ignore-window-colors true
